name: CI/CD Finance Flow

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Loading repository
        uses: actions/checkout@v4

      - name: Installing Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: 3.14

      - name: Installing requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ruff check
        run: ruff check .

      - name: Run tests
        env:
          DATABASE_URL: "sqlite+aiosqlite:///:memory:"
        run: pytest

  build-and-push:
    needs: build-and-test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Loading repository
        uses: actions/checkout@v4

      - name: Docker Hub authorization
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Release version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Pushing Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/bmi-api:latest
            ${{ secrets.DOCKER_USERNAME }}/bmi-api:${{ env.VERSION }}